
apiVersion: apps/v1
kind: Deployment
metadata: 
    name: mypythonapp
    labels: 
        app: pythonapp
spec: 
  replicas: 1
  selector:
      matchLabels: 
            app: pythonapp
  template: 
      metadata: 
           labels: 
               app: pythonapp
      spec: 
        containers: 
             - name: pythonapp
               image: rtxverma123/jenkinsbootstrap
               ports: 
                 - containerPort: 3000 
